# Generated by Django 5.2.7 on 2026-01-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='checkin_time',
        ),
        migrations.AddField(
            model_name='prize',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
