# Generated by Django 5.2.7 on 2026-01-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_remove_participant_checkin_time_prize_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='department',
        ),
    ]
