# Generated by Django 5.2.7 on 2026-01-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_remove_participant_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
