# Generated by Django 5.2.7 on 2026-01-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_participant_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='checkin_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
