# Generated by Django 5.2.7 on 2026-01-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_participant_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_on_duty',
            field=models.BooleanField(default=False, verbose_name='Đang trực'),
        ),
    ]
